[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 start_health.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Configurações para resolver service unavailable
[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"

# Configurações específicas do Railway
[deploy.healthcheck]
path = "/health"
timeout = 60
interval = 30
